server:
  port: 8082

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

kafka:
  bootstrap-servers: localhost:9092
  consumer-group:
    product: cg-products
  topic:
    product: products


